export const ActionTypes = {
  ADD_PORTFOLIO: "ADD_PORTFOLIO",
  DELETE_PORTFOLIO: "DELETE_PORTFOLIO",
  EDIT_PORTFOLIO: "EDIT_PORTFOLIO",
  RETRIEVE_PORTFOLIO_BY_ID:"RETRIEVE_PORTFOLIO_BY_ID",
  TOGGLE_LOADING:'TOGGLE_LOADING'
};
